# Generated by Django 4.2.3 on 2023-08-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_attractions', '0005_remove_attraction_user_id_remove_comment_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
