# Generated by Django 4.2.3 on 2023-08-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_attractions', '0008_rename_user_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
