# Generated by Django 4.2.3 on 2023-08-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_attractions', '0011_alter_attraction_image_alter_attraction_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
