# Generated by Django 4.2.3 on 2023-08-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_attractions', '0012_alter_attraction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(),
        ),
    ]
