# Generated by Django 4.2.3 on 2023-08-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_attractions', '0015_attraction_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='image',
            new_name='imageA',
        ),
        migrations.AddField(
            model_name='attraction',
            name='imageB',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
